### ISSUE TITLE
Adding More Examples and Check the Docs

### ISSUE THREAD

**Issue by maheraldous** [co-cart/co-cart-docs#29]
Hello

**Some example of the Docs are not work when I tested it with Postman and some of them are:**
```
https://docs.cocart.xyz/?javascript--jquery#retrieve-a-cart

 /wp-json/cocart/v1/get-cart/?cart_key=9e18904482b4faf8762361836a83b93d

/wp-json/cocart/v1/add-item/?cart_key=9e18904482b4faf8762361836a83b93d&product_id=32

 /wp-json/cocart/v1/get-cart/9e18904482b4faf8762361836a83b93d
```

**Authentication **
Note: Using Basic Authentication with Postman and verify with an account then add an item to a cart is work but when I call

`/wp-json/cocart/v1/get-cart`

The result show me all carts that made from guest and customers.

**Adding an example**
Can you add an example about how to add multiple products with different quantity in the docs?

**"thumb" : true**
`thumb` is no work and return the regular cart without the thumb data.

**Comment by seb86** [comment]
The GitHub repository is for reporting bugs.

If you have an issue with CoCart then please use the support forum where I can provide support to you.

As for the documentation the examples are correct and I cant add documentation for something that is not supported.
